// src/components/miniapp/editor/ShareSheet.jsx
/**
 * ShareSheet —— 分享面板
 *
 * 支持把当前袜版设计 / 当前页面分享到微信好友、朋友圈、群聊。
 * 因小程序原型为前端展示，分享走"模拟"流程：渲染分享卡片 + 弹出来源选择，点击后回调 onShared。
 */
import { useEffect, useState } from 'react'
import { Share2, MessageCircle, Users, Image as ImageIcon, Link as LinkIcon, Loader2, Copy, Check } from 'lucide-react'
import BottomSheet from './BottomSheet'

const TARGETS = [
  { key: 'wechat',  label: '微信好友', icon: MessageCircle, color: '#07c160' },
  { key: 'moments', label: '朋友圈',   icon: ImageIcon,     color: '#1aad19' },
  { key: 'group',   label: '群聊',     icon: Users,         color: '#3a6fb0' },
]

export default function ShareSheet({ design, getCover, onClose, onShared }) {
  const [cover, setCover] = useState(null)
  const [coverLoading, setCoverLoading] = useState(true)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    let alive = true
    ;(async () => {
      setCoverLoading(true)
      try {
        const url = await getCover?.()
        if (alive) setCover(url || null)
      } finally {
        if (alive) setCoverLoading(false)
      }
    })()
    return () => { alive = false }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const shareLink = `https://aihuaxing.cn/s/${(design?.printName || design?.name || 'design').slice(0, 16)}`

  const handleShareTo = (target) => {
    onShared?.(target.label)
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard?.writeText?.(shareLink)
    } catch { /* noop */ }
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  return (
    <BottomSheet
      title={
        <span className="mp-pay-title-row">
          <Share2 size={13} /> 分享设计
        </span>
      }
      subtitle="把这件袜款分享给朋友，邀请一起设计"
      onClose={onClose}
    >
      {/* 分享卡片预览 */}
      <div className="mp-share-card">
        <div className="mp-share-card-cover">
          {coverLoading ? (
            <div className="mp-share-card-loading">
              <Loader2 size={18} className="mp-spin"/>
            </div>
          ) : cover ? (
            <img src={cover} alt={design?.name || '袜版'} />
          ) : (
            <div className="mp-share-card-empty">暂无预览</div>
          )}
        </div>
        <div className="mp-share-card-meta">
          <div className="mp-share-card-title">{design?.name || '我的袜版'}</div>
          <div className="mp-share-card-sub">爱花型 · AI 袜版定制</div>
          <div className="mp-share-card-tag">点开即可同款再创作</div>
        </div>
      </div>

      {/* 链接 */}
      <div className="mp-share-link">
        <LinkIcon size={11} strokeWidth={1.6}/>
        <span className="mp-share-link-url">{shareLink}</span>
        <button className="mp-share-link-copy" onClick={handleCopy}>
          {copied ? <><Check size={11}/> 已复制</> : <><Copy size={11}/> 复制</>}
        </button>
      </div>

      {/* 分享渠道 */}
      <div className="mp-share-targets">
        {TARGETS.map((t) => {
          const Icon = t.icon
          return (
            <button
              key={t.key}
              className="mp-share-target"
              onClick={() => handleShareTo(t)}
            >
              <span
                className="mp-share-target-icon"
                style={{ background: `${t.color}15`, color: t.color }}
              >
                <Icon size={18} strokeWidth={1.8}/>
              </span>
              <span className="mp-share-target-label">{t.label}</span>
            </button>
          )
        })}
      </div>

      <div className="mp-share-tip">
        分享后好友可一键同款再创作，邀请新用户注册可获得额外 AI 生图次数
      </div>
    </BottomSheet>
  )
}

// miniprogram/packages/app/src/components/editor/ShareSheet.vue
<template>
  <BottomSheet title="分享设计" subtitle="把这件袜款分享给朋友，邀请一起设计" @close="$emit('close')">
    <!-- 分享卡片 -->
    <view class="share-card">
      <view class="share-cover">
        <image v-if="cover" :src="cover" mode="aspectFill" class="cover-img" />
        <view v-else class="cover-empty">🧦</view>
      </view>
      <view class="share-meta">
        <text class="share-title">{{ design.name || '我的袜版' }}</text>
        <text class="share-sub">爱花型 · AI 袜版定制</text>
        <text class="share-tag">点开即可同款再创作</text>
      </view>
    </view>

    <!-- 链接 -->
    <view class="share-link">
      <text class="link-url">{{ shareLink }}</text>
      <view class="link-copy" @tap="onCopy">{{ copied ? '已复制' : '复制' }}</view>
    </view>

    <!-- 渠道 -->
    <view class="targets">
      <button class="target" open-type="share" @tap="onShareTo('微信好友')">
        <view class="target-icon" style="background: rgba(7,193,96,0.12); color: #07c160">💬</view>
        <text class="target-label">微信好友</text>
      </button>
      <view class="target" @tap="onShareTo('朋友圈')">
        <view class="target-icon" style="background: rgba(26,173,25,0.12); color: #1aad19">🌄</view>
        <text class="target-label">朋友圈</text>
      </view>
      <view class="target" @tap="onShareTo('群聊')">
        <view class="target-icon" style="background: rgba(58,111,176,0.12); color: #3a6fb0">👥</view>
        <text class="target-label">群聊</text>
      </view>
    </view>

    <view class="share-tip">分享后好友可一键同款再创作，邀请新用户注册可获得额外 AI 生图次数</view>
  </BottomSheet>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import BottomSheet from '@/components/BottomSheet.vue'
import { aiApi } from '@aisock/service'

const props = defineProps<{ design: { name?: string; printName?: string }; cover?: string | null }>()
const emit = defineEmits<{ close: []; shared: [target: string] }>()

const copied = ref(false)
const shareLink = computed(() => `https://aihuaxing.cn/s/${(props.design.printName || props.design.name || 'design').slice(0, 16)}`)

function onCopy() {
  uni.setClipboardData({
    data: shareLink.value,
    success: () => {
      copied.value = true
      setTimeout(() => (copied.value = false), 1500)
    },
  })
}

async function onShareTo(target: string) {
  // 分享成功后给当前用户加邀请奖励（演示：直接调用）
  try {
    await aiApi.inviteBonus(3)
  } catch {
    /* 忽略 */
  }
  emit('shared', target)
}
</script>

<style scoped lang="scss">
@import '@aisock/common/styles/variables.scss';

.share-card {
  display: flex;
  gap: 20rpx;
  background: $mp-bg;
  border-radius: 20rpx;
  padding: 20rpx;
  margin-bottom: 20rpx;
}
.share-cover {
  width: 160rpx;
  height: 160rpx;
  border-radius: 16rpx;
  overflow: hidden;
  flex-shrink: 0;
  background: $mp-bg-card;
}
.cover-img {
  width: 100%;
  height: 100%;
}
.cover-empty {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 60rpx;
}
.share-meta {
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  gap: 8rpx;
}
.share-title {
  font-size: 28rpx;
  font-weight: 700;
  color: $mp-text-primary;
}
.share-sub {
  font-size: 22rpx;
  color: $mp-text-muted;
}
.share-tag {
  font-size: 20rpx;
  color: $mp-primary;
  background: $mp-primary-soft;
  padding: 4rpx 14rpx;
  border-radius: 999rpx;
  align-self: flex-start;
}
.share-link {
  display: flex;
  align-items: center;
  gap: 12rpx;
  background: $mp-bg;
  border-radius: 14rpx;
  padding: 16rpx 20rpx;
  margin-bottom: 24rpx;
}
.link-url {
  flex: 1;
  font-size: 22rpx;
  color: $mp-text-secondary;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
.link-copy {
  font-size: 22rpx;
  color: $mp-primary;
  flex-shrink: 0;
}
.targets {
  display: flex;
  justify-content: space-around;
  margin-bottom: 24rpx;
}
.target {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 10rpx;
  background: transparent;
  border: none;
  padding: 0;
  line-height: 1.2;
}
.target::after {
  border: none;
}
.target-icon {
  width: 88rpx;
  height: 88rpx;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 40rpx;
}
.target-label {
  font-size: 22rpx;
  color: $mp-text-secondary;
}
.share-tip {
  font-size: 20rpx;
  color: $mp-text-muted;
  line-height: 1.6;
  text-align: center;
}
</style>
