// miniprogram/packages/app/src/components/editor/OrderSheet.vue
<template>
  <BottomSheet title="提交订单" :subtitle="`${total} 双 · 5 分钟交付`" size="tall" @close="$emit('close')">
    <view class="form">
      <view class="field">
        <text class="field-label">设计名称</text>
        <input v-model="designName" class="ipt" placeholder="给这个袜版取个名字" />
      </view>

      <view class="field">
        <text class="field-label">尺码与数量</text>
        <view v-for="s in sizeList" :key="s" class="size-line">
          <text class="size-tag">{{ s }}</text>
          <view class="step-btn" @tap="stepSize(s, -10)">−</view>
          <input type="number" :value="sizes[s]" class="size-ipt" @input="onSizeInput(s, $event)" />
          <view class="step-btn" @tap="stepSize(s, 10)">＋</view>
          <text class="size-unit">双</text>
        </view>
        <view class="size-total">合计 <text class="total-num">{{ total }}</text> 双</view>
      </view>

      <view class="field">
        <text class="field-label">面料材质</text>
        <view class="chip-row">
          <view v-for="m in materials" :key="m.value" :class="['chip-card', { active: material === m.value }]" @tap="material = m.value">
            <text class="chip-name">{{ m.label }}</text>
            <text class="chip-desc">{{ m.desc }}</text>
          </view>
        </view>
      </view>

      <view class="field">
        <text class="field-label">工艺选型</text>
        <view class="chip-row">
          <view v-for="c in crafts" :key="c.value" :class="['chip-card', { active: craft === c.value }]" @tap="craft = c.value">
            <text class="chip-name">{{ c.label }}</text>
            <text class="chip-desc">{{ c.desc }}</text>
          </view>
        </view>
      </view>

      <view class="field">
        <text class="field-label">收货信息</text>
        <view class="input-row">
          <input v-model="contact" class="ipt" placeholder="联系人" />
          <input v-model="phone" class="ipt" type="number" placeholder="手机号" />
        </view>
        <input v-model="address" class="ipt" placeholder="详细地址（省/市/区/街道）" />
      </view>

      <view class="field">
        <text class="field-label">备注（选填）</text>
        <textarea v-model="note" class="ipt textarea" placeholder="包装要求、加急说明等" />
      </view>
    </view>

    <template #footer>
      <view class="footer-row">
        <button class="cta secondary" @tap="$emit('close')">取消</button>
        <button class="cta primary" :disabled="!canSubmit" @tap="submit">下一步：去支付</button>
      </view>
    </template>
  </BottomSheet>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import BottomSheet from '@/components/BottomSheet.vue'
import { MATERIALS, CRAFTS, SIZE_LIST } from '@aisock/common'

const props = defineProps<{ defaultDesignName?: string }>()
const emit = defineEmits<{ close: []; submit: [data: OrderData] }>()

interface OrderData {
  designName: string
  sizes: Record<string, number>
  total: number
  material: string
  materialValue: string
  craft: string
  craftValue: string
  contact: string
  phone: string
  address: string
  note: string
}

const materials = MATERIALS
const crafts = CRAFTS
const sizeList = SIZE_LIST

const designName = ref(props.defaultDesignName || '未命名袜版')
const sizes = reactive<Record<string, number>>({ S: 0, M: 50, L: 30, XL: 0 })
const material = ref('cotton')
const craft = ref('uv')
const contact = ref('')
const phone = ref('')
const address = ref('')
const note = ref('')

const total = computed(() => Object.values(sizes).reduce((a, b) => a + b, 0))
const canSubmit = computed(() => total.value > 0 && !!contact.value.trim() && !!phone.value.trim() && !!address.value.trim())

function stepSize(s: string, delta: number) {
  sizes[s] = Math.max(0, sizes[s] + delta)
}
function onSizeInput(s: string, e: any) {
  sizes[s] = Math.max(0, Number(e.detail.value) || 0)
}
function submit() {
  if (!canSubmit.value) return
  const m = materials.find((x) => x.value === material.value)
  const c = crafts.find((x) => x.value === craft.value)
  emit('submit', {
    designName: designName.value,
    sizes: Object.fromEntries(Object.entries(sizes).filter(([, v]) => v > 0)),
    total: total.value,
    material: m?.label || '棉',
    materialValue: material.value,
    craft: c?.label || 'UV 印花',
    craftValue: craft.value,
    contact: contact.value,
    phone: phone.value,
    address: address.value,
    note: note.value,
  })
}
</script>

<style scoped lang="scss">
@import '@aisock/common/styles/variables.scss';

.field {
  margin-bottom: 24rpx;
}
.field-label {
  display: block;
  font-size: 24rpx;
  font-weight: 600;
  color: $mp-text-primary;
  margin-bottom: 12rpx;
}
.ipt {
  width: 100%;
  height: 76rpx;
  border: 1rpx solid $mp-border;
  border-radius: 14rpx;
  padding: 0 20rpx;
  font-size: 26rpx;
  background: $mp-bg-card;
  box-sizing: border-box;
}
.textarea {
  height: 120rpx;
  padding: 16rpx 20rpx;
}
.input-row {
  display: flex;
  gap: 12rpx;
  margin-bottom: 12rpx;
}
.input-row .ipt {
  flex: 1;
}
.size-line {
  display: flex;
  align-items: center;
  gap: 12rpx;
  margin-bottom: 12rpx;
}
.size-tag {
  width: 50rpx;
  font-size: 26rpx;
  font-weight: 600;
  color: $mp-text-primary;
}
.step-btn {
  width: 56rpx;
  height: 56rpx;
  border-radius: 12rpx;
  border: 1rpx solid $mp-border;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 30rpx;
  color: $mp-text-secondary;
}
.size-ipt {
  width: 120rpx;
  height: 56rpx;
  border: 1rpx solid $mp-border;
  border-radius: 12rpx;
  text-align: center;
  font-size: 26rpx;
}
.size-unit {
  font-size: 24rpx;
  color: $mp-text-muted;
}
.size-total {
  text-align: right;
  font-size: 24rpx;
  color: $mp-text-secondary;
  margin-top: 8rpx;
}
.total-num {
  color: $mp-primary;
  font-weight: 700;
  font-size: 30rpx;
}
.chip-row {
  display: flex;
  gap: 12rpx;
}
.chip-card {
  flex: 1;
  padding: 16rpx;
  border: 1rpx solid $mp-border;
  border-radius: 14rpx;
  display: flex;
  flex-direction: column;
  gap: 4rpx;
}
.chip-card.active {
  border-color: $mp-primary;
  background: $mp-primary-soft;
}
.chip-name {
  font-size: 26rpx;
  font-weight: 600;
  color: $mp-text-primary;
}
.chip-desc {
  font-size: 20rpx;
  color: $mp-text-muted;
}
.footer-row {
  display: flex;
  gap: 16rpx;
}
.cta {
  flex: 1;
  height: 84rpx;
  line-height: 84rpx;
  border-radius: 999rpx;
  font-size: 28rpx;
  padding: 0;
}
.cta.secondary {
  background: $mp-bg;
  color: $mp-text-secondary;
}
.cta.primary {
  background: $mp-primary;
  color: #fff;
}
.cta.primary[disabled] {
  opacity: 0.5;
}
</style>

// src/components/miniapp/editor/OrderSheet.jsx
/**
 * OrderSheet — 下单填表（移动版 OrderModal）
 * 复用 web 端 MATERIALS / CRAFTS 常量，确保业务参数一致
 */
import { useMemo, useState } from 'react'
import BottomSheet from './BottomSheet'
import { MATERIALS, CRAFTS } from '../../print/printConstants'

const SIZE_LIST = ['S', 'M', 'L', 'XL']

export default function OrderSheet({ defaultDesignName, onClose, onSubmit }) {
  const [designName, setDesignName] = useState(defaultDesignName || '未命名袜版')
  const [sizes, setSizes] = useState({ S: 0, M: 50, L: 30, XL: 0 })
  const [material, setMaterial] = useState('cotton')
  const [craft, setCraft] = useState('uv')
  const [contact, setContact] = useState('')
  const [phone, setPhone] = useState('')
  const [address, setAddress] = useState('')
  const [note, setNote] = useState('')

  const total = useMemo(
    () => Object.values(sizes).reduce((a, b) => a + b, 0),
    [sizes],
  )
  const canSubmit = total > 0 && contact.trim() && phone.trim() && address.trim()

  const setSize = (s, v) => setSizes((p) => ({ ...p, [s]: Math.max(0, Number(v) || 0) }))
  const stepSize = (s, delta) => setSizes((p) => ({ ...p, [s]: Math.max(0, p[s] + delta) }))

  const handleSubmit = () => {
    if (!canSubmit) return
    const m = MATERIALS.find((x) => x.value === material)
    const c = CRAFTS.find((x) => x.value === craft)
    onSubmit?.({
      designName,
      sizes: Object.fromEntries(Object.entries(sizes).filter(([, v]) => v > 0)),
      total,
      material: m?.label || '棉',
      materialValue: material,
      craft: c?.label || 'UV 印花',
      craftValue: craft,
      contact, phone, address, note,
    })
  }

  return (
    <BottomSheet
      title="提交订单"
      subtitle={`${total} 双 · 5 分钟交付`}
      onClose={onClose}
      size="tall"
      footer={
        <div className="mp-sheet-footer-row">
          <button className="mp-cta-secondary" onClick={onClose}>取消</button>
          <button
            className="mp-cta-primary"
            disabled={!canSubmit}
            onClick={handleSubmit}
          >
            下一步：去支付
          </button>
        </div>
      }
    >
      <div className="mp-form">
        <Field label="设计名称">
          <input
            className="mp-input"
            value={designName}
            onChange={(e) => setDesignName(e.target.value)}
            placeholder="给这个袜版取个名字"
          />
        </Field>

        <Field label="尺码与数量">
          {SIZE_LIST.map((s) => (
            <div key={s} className="mp-size-line">
              <span className="mp-size-tag">{s}</span>
              <button className="mp-step-btn" onClick={() => stepSize(s, -10)} disabled={sizes[s] === 0}>−</button>
              <input
                type="number"
                min="0"
                value={sizes[s]}
                onChange={(e) => setSize(s, e.target.value)}
                className="mp-size-input"
              />
              <button className="mp-step-btn" onClick={() => stepSize(s, +10)}>+</button>
              <span className="mp-size-unit">双</span>
            </div>
          ))}
          <div className="mp-size-total">
            合计 <b>{total}</b> 双
          </div>
        </Field>

        <Field label="面料材质">
          <div className="mp-chip-row">
            {MATERIALS.map((m) => (
              <button
                key={m.value}
                className={`mp-chip-card ${material === m.value ? 'active' : ''}`}
                onClick={() => setMaterial(m.value)}
              >
                <span className="mp-chip-card-name">{m.label}</span>
                <span className="mp-chip-card-desc">{m.desc}</span>
              </button>
            ))}
          </div>
        </Field>

        <Field label="工艺选型">
          <div className="mp-chip-row">
            {CRAFTS.map((c) => (
              <button
                key={c.value}
                className={`mp-chip-card ${craft === c.value ? 'active' : ''}`}
                onClick={() => setCraft(c.value)}
              >
                <span className="mp-chip-card-name">{c.label}</span>
                <span className="mp-chip-card-desc">{c.desc}</span>
              </button>
            ))}
          </div>
        </Field>

        <Field label="收货信息">
          <div className="mp-input-row">
            <input
              className="mp-input"
              value={contact}
              onChange={(e) => setContact(e.target.value)}
              placeholder="联系人"
            />
            <input
              className="mp-input"
              value={phone}
              onChange={(e) => setPhone(e.target.value)}
              placeholder="手机号"
            />
          </div>
          <input
            className="mp-input"
            value={address}
            onChange={(e) => setAddress(e.target.value)}
            placeholder="详细地址（省/市/区/街道）"
          />
        </Field>

        <Field label="备注（选填）">
          <textarea
            className="mp-input mp-textarea"
            value={note}
            onChange={(e) => setNote(e.target.value)}
            placeholder="包装要求、加急说明等"
            rows={2}
          />
        </Field>
      </div>
    </BottomSheet>
  )
}

function Field({ label, children }) {
  return (
    <div className="mp-form-field">
      <label className="mp-form-label">{label}</label>
      <div className="mp-form-content">{children}</div>
    </div>
  )
}
