// web/src/components/editor/AssetPanel.vue
<template>
  <aside class="asset-panel">
    <div class="asset-tabs">
      <button v-for="t in tabs" :key="t.key" :class="['asset-tab', { active: tab === t.key }]" @click="tab = t.key">
        {{ t.label }}
      </button>
    </div>

    <!-- 公共库 -->
    <template v-if="tab === 'library'">
      <div class="asset-search">
        <input v-model="query" placeholder="搜索花型" />
      </div>
      <div class="asset-tip">拖拽花型到袜版即可应用，双击直接贴印</div>
      <div class="asset-grid">
        <div
          v-for="p in filteredPatterns"
          :key="p.id"
          class="asset-item"
          draggable="true"
          :title="`${p.name} · 拖到袜版即可应用`"
          @dragstart="onDragStart($event, p.id, p.name)"
          @click="$emit('apply', p.id, p.name)"
        >
          <div class="asset-swatch"><PatternSwatch :pattern-id="p.id" :uid="`a-${p.id}`" /></div>
          <span class="asset-name">{{ p.name }}</span>
        </div>
      </div>
    </template>

    <!-- 我的 -->
    <template v-else-if="tab === 'mine'">
      <button class="mine-upload" @click="pickFile">⬆ 上传到我的素材库</button>
      <input ref="fileInput" type="file" accept="image/*" hidden @change="onFileChange" />
      <div v-if="mine.length === 0" class="mine-empty">
        <p>个人素材库为空</p>
        <small>上传你喜欢的图片，让设计更随心</small>
      </div>
      <div v-else class="asset-grid">
        <div
          v-for="m in mine"
          :key="m.id"
          class="asset-item"
          draggable="true"
          @dragstart="onDragImageStart($event, m.url, m.name)"
          @click="$emit('applyImage', m.url, m.name)"
        >
          <div class="asset-swatch"><img :src="m.url" :alt="m.name" /></div>
          <span class="asset-name">{{ m.name }}</span>
        </div>
      </div>
    </template>

    <!-- AI 生成 -->
    <template v-else-if="tab === 'ai'">
      <div class="ai-hint">描述想要的花型，一键生成同款</div>
      <textarea v-model="prompt" class="ai-textarea" placeholder="如：春日樱花飘落，粉色为主，少量金色点缀" />
      <button class="ai-submit" :disabled="!prompt.trim() || generating" @click="onGenerate">
        {{ generating ? '生成中…' : '生成花型' }}
      </button>
      <div class="ai-presets">
        <button v-for="p in aiPresets" :key="p" class="ai-preset" @click="prompt = p">{{ p }}</button>
      </div>
    </template>

    <!-- 历史 -->
    <template v-else>
      <div v-if="history.length === 0" class="history-empty">还没有生成记录，去 AI 生成试一下吧</div>
      <div v-else class="asset-history">
        <div v-for="h in history" :key="h.id" class="history-item">
          <img :src="h.url" :alt="h.prompt" class="history-thumb" />
          <div class="history-info">
            <div class="history-prompt">{{ h.prompt }}</div>
            <div class="history-meta">可应用</div>
          </div>
          <button class="history-apply" @click="$emit('applyImage', h.url, h.prompt)">应用</button>
        </div>
      </div>
    </template>
  </aside>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import PatternSwatch from '@/components/PatternSwatch.vue'
import { PATTERN_LIST, AI_PRESETS } from '@/data/editor'
import { aiApi } from '@/api'

const emit = defineEmits<{
  apply: [patternId: string, name: string]
  applyImage: [url: string, name: string]
}>()

const tabs = [
  { key: 'library', label: '公共库' },
  { key: 'mine', label: '我的' },
  { key: 'ai', label: 'AI 生成' },
  { key: 'history', label: '历史' },
]
const tab = ref('library')
const query = ref('')
const prompt = ref('')
const generating = ref(false)
const aiPresets = AI_PRESETS

const fileInput = ref<HTMLInputElement | null>(null)
const mine = ref<{ id: number; url: string; name: string }[]>([])
const history = ref<{ id: number; url: string; prompt: string }[]>([])

const filteredPatterns = computed(() =>
  PATTERN_LIST.filter((p) => !query.value || p.name.includes(query.value)),
)

function onDragStart(e: DragEvent, patternId: string, name: string) {
  e.dataTransfer?.setData('application/x-aisock-pattern', patternId)
  e.dataTransfer?.setData('application/x-aisock-name', name)
}
function onDragImageStart(e: DragEvent, url: string, name: string) {
  e.dataTransfer?.setData('application/x-aisock-image', url)
  e.dataTransfer?.setData('application/x-aisock-name', name)
}

function pickFile() {
  fileInput.value?.click()
}
function onFileChange(e: Event) {
  const file = (e.target as HTMLInputElement).files?.[0]
  if (!file) return
  const reader = new FileReader()
  reader.onload = (ev) => {
    mine.value.unshift({ id: Date.now(), url: ev.target?.result as string, name: file.name.replace(/\.[^.]+$/, '') })
  }
  reader.readAsDataURL(file)
  ;(e.target as HTMLInputElement).value = ''
}

async function onGenerate() {
  if (!prompt.value.trim() || generating.value) return
  generating.value = true
  try {
    const res = await aiApi.generate({ type: 'text2img', prompt: prompt.value })
    const url = res.data.result_urls?.[0]
    if (url) {
      history.value.unshift({ id: Date.now(), url, prompt: prompt.value })
      emit('applyImage', url, prompt.value)
      tab.value = 'history'
    }
  } catch (e) {
    alert((e as Error).message)
  } finally {
    generating.value = false
  }
}
</script>

<style scoped>
.asset-panel {
  width: 240px;
  flex-shrink: 0;
  background: var(--bg-card);
  border-right: 1px solid var(--border);
  display: flex;
  flex-direction: column;
  overflow-y: auto;
  padding: 12px;
}
.asset-tabs {
  display: flex;
  gap: 4px;
  margin-bottom: 12px;
}
.asset-tab {
  flex: 1;
  padding: 7px 0;
  font-size: 12px;
  border: none;
  background: var(--bg-hover);
  border-radius: 8px;
  color: var(--text-2);
}
.asset-tab.active {
  background: var(--primary);
  color: #fff;
  font-weight: 600;
}
.asset-search input {
  width: 100%;
  height: 32px;
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 0 10px;
  font-size: 12px;
}
.asset-tip {
  font-size: 11px;
  color: var(--text-3);
  margin: 8px 0;
}
.asset-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 10px;
}
.asset-item {
  cursor: grab;
  border-radius: 10px;
  overflow: hidden;
  border: 1px solid var(--border);
  background: var(--bg-card);
  transition: transform 0.15s;
}
.asset-item:hover {
  transform: translateY(-2px);
  box-shadow: var(--shadow-sm);
}
.asset-swatch {
  aspect-ratio: 1;
}
.asset-swatch img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
.asset-name {
  display: block;
  font-size: 11px;
  text-align: center;
  padding: 5px;
  color: var(--text-2);
}
.mine-upload {
  width: 100%;
  height: 36px;
  border: 1px dashed var(--border-strong);
  border-radius: 8px;
  background: var(--bg-hover);
  color: var(--text-2);
  font-size: 12px;
  margin-bottom: 10px;
}
.mine-empty,
.history-empty {
  text-align: center;
  color: var(--text-3);
  font-size: 12px;
  padding: 40px 0;
}
.mine-empty small {
  display: block;
  margin-top: 4px;
  font-size: 11px;
}
.ai-hint {
  font-size: 12px;
  color: var(--text-2);
  margin-bottom: 10px;
}
.ai-textarea {
  width: 100%;
  height: 90px;
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 10px;
  font-size: 12px;
  resize: vertical;
  font-family: inherit;
}
.ai-submit {
  width: 100%;
  height: 36px;
  margin-top: 10px;
  background: var(--primary);
  color: #fff;
  border: none;
  border-radius: 8px;
  font-size: 13px;
  font-weight: 600;
}
.ai-submit:disabled {
  opacity: 0.5;
}
.ai-presets {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-top: 10px;
}
.ai-preset {
  font-size: 11px;
  padding: 4px 10px;
  border: 1px solid var(--border);
  border-radius: 999px;
  background: var(--bg-card);
  color: var(--text-2);
}
.asset-history {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.history-item {
  display: flex;
  align-items: center;
  gap: 8px;
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 6px;
}
.history-thumb {
  width: 40px;
  height: 40px;
  border-radius: 6px;
  object-fit: cover;
}
.history-info {
  flex: 1;
  min-width: 0;
}
.history-prompt {
  font-size: 12px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.history-meta {
  font-size: 10px;
  color: var(--text-3);
}
.history-apply {
  font-size: 11px;
  padding: 4px 10px;
  border: none;
  border-radius: 6px;
  background: var(--primary-soft);
  color: var(--primary);
}
</style>

// src/components/AssetPanel.jsx
import { useMemo, useRef, useState } from 'react'
import './AssetPanel.css'
import { Sparkles, Search, MousePointerClick, Upload, Trash2, X, ImageIcon } from 'lucide-react'
import { PATTERN_LIST } from './patternConstants'
import { PatternDefs } from './patterns'
import { aiGenerateImage, patternToImageURL } from './patternImage'
import useAssetLibrary from './assets/useAssetLibrary'

const TABS = [
  { key: 'library', label: '公共库' },
  { key: 'mine',    label: '我的' },
  { key: 'ai',      label: 'AI 生成' },
  { key: 'history', label: '历史' },
]

const PRESETS = ['春日樱花', '海蓝清爽', '复古条纹', '简约几何', '金色奢华', '薄荷清新']

const makeDragHandler = (url, name) => (e) => {
  e.dataTransfer.effectAllowed = 'copy'
  e.dataTransfer.setData('text/uri-list', url)
  e.dataTransfer.setData('text/plain', url)
  e.dataTransfer.setData('application/x-aisock-pattern', url)
  e.dataTransfer.setData('application/x-aisock-name', name || '')
  try {
    const ghost = new Image()
    ghost.src = url
    e.dataTransfer.setDragImage(ghost, 30, 30)
  } catch { /* ignore */ }
}

export default function AssetPanel({ onApplyImage }) {
  const [tab, setTab] = useState('library')
  const [query, setQuery] = useState('')
  const [aiPrompt, setAiPrompt] = useState('')
  const [refImage, setRefImage] = useState(null)   // AI 延申参考图（dataURL）
  const [refName, setRefName] = useState('')
  const [generating, setGenerating] = useState(false)
  const [history, setHistory] = useState([])
  const refInputRef = useRef(null)

  const lib = useAssetLibrary()

  const officialItems = useMemo(
    () => PATTERN_LIST.map((p) => ({
      id: p.id,
      name: p.name,
      url: patternToImageURL(p.id, 240),
      tags: ['官方'],
      svg: true,
    })),
    [],
  )

  // 公共库 = 内置 + 管理员上架
  const publicItems = useMemo(() => {
    const adminOnline = lib.publicAssets.filter((a) => a.online !== false)
    return [...officialItems, ...adminOnline]
  }, [officialItems, lib.publicAssets])

  const filteredPublic = publicItems.filter((p) => !query || (p.name || '').includes(query))

  const handleAiGenerate = async () => {
    if (!aiPrompt.trim() || generating) return
    setGenerating(true)
    const result = await aiGenerateImage(aiPrompt)
    const promptLabel = refImage ? `${aiPrompt} · 延申` : aiPrompt
    const item = {
      id: Date.now(),
      prompt: promptLabel,
      basePid: result.basePid,
      url: result.url,
      refUrl: refImage,
    }
    setHistory((prev) => [item, ...prev].slice(0, 24))
    setGenerating(false)
    onApplyImage?.(item.url, promptLabel)
    setTab('history')
  }

  const handleSetRefFromFile = async (file) => {
    if (!file?.type?.startsWith('image/')) return
    const reader = new FileReader()
    reader.onload = (e) => {
      setRefImage(e.target.result)
      setRefName(file.name?.replace(/\.[^/.]+$/, '') || '本地参考图')
    }
    reader.readAsDataURL(file)
  }

  return (
    <aside className="asset-panel">
      <div className="asset-tabs">
        {TABS.map((t) => (
          <button
            key={t.key}
            className={`asset-tab ${tab === t.key ? 'active' : ''}`}
            onClick={() => setTab(t.key)}
          >
            {t.label}
          </button>
        ))}
      </div>

      {tab === 'library' && (
        <PublicTab
          items={filteredPublic}
          query={query}
          onQueryChange={setQuery}
          onApplyImage={onApplyImage}
        />
      )}

      {tab === 'mine' && (
        <MineTab
          items={lib.userAssets}
          onUpload={lib.addUserAsset}
          onRemove={lib.removeUserAsset}
          onApplyImage={onApplyImage}
        />
      )}

      {tab === 'ai' && (
        <AiTab
          prompt={aiPrompt}
          onPromptChange={setAiPrompt}
          generating={generating}
          onGenerate={handleAiGenerate}
          refImage={refImage}
          refName={refName}
          onRefFromFile={handleSetRefFromFile}
          onRefFromMine={(asset) => { setRefImage(asset.url); setRefName(asset.name) }}
          onClearRef={() => { setRefImage(null); setRefName('') }}
          mineAssets={lib.userAssets}
          refInputRef={refInputRef}
        />
      )}

      {tab === 'history' && (
        <HistoryTab history={history} onApplyImage={onApplyImage} />
      )}
    </aside>
  )
}

function PublicTab({ items, query, onQueryChange, onApplyImage }) {
  return (
    <>
      <div className="asset-search">
        <Search size={13} strokeWidth={1.6} />
        <input
          placeholder="搜索花型"
          value={query}
          onChange={(e) => onQueryChange(e.target.value)}
        />
      </div>
      <div className="asset-drag-tip">
        <MousePointerClick size={11} strokeWidth={1.6} />
        拖拽花型到袜版即可应用，双击直接贴印
      </div>
      <div className="asset-grid">
        {items.map((p) => (
          <PublicItem key={p.id} item={p} onApply={onApplyImage} />
        ))}
      </div>
    </>
  )
}

function PublicItem({ item, onApply }) {
  return (
    <div
      className="asset-item"
      title={`${item.name} · 拖到袜版即可应用`}
      draggable
      onDragStart={makeDragHandler(item.url, item.name)}
      onDoubleClick={() => onApply?.(item.url, item.name)}
      onClick={() => onApply?.(item.url, item.name)}
    >
      {item.svg ? (
        <svg viewBox="0 0 60 60" width="100%" height="100%">
          <PatternDefs uid={`a-${item.id}`} />
          <rect width="60" height="60" rx="8" fill={`url(#${item.id}-a-${item.id})`} />
        </svg>
      ) : (
        <img src={item.url} alt={item.name} className="asset-item-img" />
      )}
      <span className="asset-item-name">{item.name}</span>
    </div>
  )
}

function MineTab({ items, onUpload, onRemove, onApplyImage }) {
  const inputRef = useRef(null)
  const handlePick = () => inputRef.current?.click()
  const handleChange = async (e) => {
    const file = e.target.files?.[0]
    if (file) await onUpload(file)
    e.target.value = ''
  }

  return (
    <div className="asset-mine">
      <input ref={inputRef} type="file" accept="image/*" onChange={handleChange} hidden />
      <button className="mine-upload-btn" onClick={handlePick} type="button">
        <Upload size={13} strokeWidth={1.6} />
        上传到我的素材库
      </button>
      <div className="asset-drag-tip soft">
        上传后可在这里随时拖到袜版，也可作为 AI 延申的参考图
      </div>

      {items.length === 0 ? (
        <div className="mine-empty">
          <ImageIcon size={26} strokeWidth={1.2} />
          <p>个人素材库为空</p>
          <small>上传你喜欢的图片，让设计更随心</small>
        </div>
      ) : (
        <div className="asset-grid">
          {items.map((it) => (
            <div
              key={it.id}
              className="asset-item asset-item-removable"
              draggable
              onDragStart={makeDragHandler(it.url, it.name)}
              onDoubleClick={() => onApplyImage?.(it.url, it.name)}
              onClick={() => onApplyImage?.(it.url, it.name)}
              title={`${it.name} · 双击应用 / 拖拽到袜版`}
            >
              <img src={it.url} alt={it.name} className="asset-item-img" />
              <span className="asset-item-name">{it.name}</span>
              <button
                type="button"
                className="asset-item-remove"
                aria-label="删除"
                onClick={(e) => { e.stopPropagation(); onRemove(it.id) }}
              >
                <Trash2 size={11} strokeWidth={1.8} />
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

function AiTab({
  prompt, onPromptChange,
  generating, onGenerate,
  refImage, refName,
  onRefFromFile, onClearRef,
  onRefFromMine,
  mineAssets,
  refInputRef,
}) {
  const [picker, setPicker] = useState(null)  // null | 'mine'
  const handlePickFile = () => refInputRef.current?.click()
  const handleFileChange = (e) => {
    const f = e.target.files?.[0]
    if (f) onRefFromFile(f)
    e.target.value = ''
  }

  return (
    <div className="asset-ai">
      <input ref={refInputRef} type="file" accept="image/*" onChange={handleFileChange} hidden />

      <div className="ai-hint">
        <Sparkles size={14} strokeWidth={1.6} />
        描述想要的花型，可选上传 / 选取参考图做"图片延申"
      </div>

      <div className="ai-ref">
        <div className="ai-ref-label">参考图（可选）</div>
        {refImage ? (
          <div className="ai-ref-card">
            <img src={refImage} alt="参考" />
            <div className="ai-ref-meta">
              <div className="ai-ref-name">{refName}</div>
              <div className="ai-ref-tip">基于此图生成同款变体</div>
            </div>
            <button
              type="button"
              className="ai-ref-clear"
              onClick={onClearRef}
              aria-label="清除参考图"
            >
              <X size={12} strokeWidth={2} />
            </button>
          </div>
        ) : (
          <div className="ai-ref-empty">
            <button type="button" className="ai-ref-btn" onClick={handlePickFile}>
              <Upload size={11} /> 本地上传
            </button>
            <button
              type="button"
              className="ai-ref-btn"
              onClick={() => setPicker('mine')}
              disabled={mineAssets.length === 0}
              title={mineAssets.length === 0 ? '个人库为空，先到"我的"上传' : '从我的素材库选取'}
            >
              <ImageIcon size={11} /> 个人库选取
            </button>
          </div>
        )}
      </div>

      <textarea
        className="ai-textarea"
        placeholder="如：春日樱花飘落，粉色为主，少量金色点缀"
        value={prompt}
        onChange={(e) => onPromptChange(e.target.value)}
      />
      <button
        className="ai-submit"
        disabled={!prompt.trim() || generating}
        onClick={onGenerate}
      >
        {generating ? '生成中…' : refImage ? '基于参考图生成' : '生成花型'}
      </button>
      <div className="ai-presets">
        {PRESETS.map((p) => (
          <button key={p} className="ai-preset" onClick={() => onPromptChange(p)}>{p}</button>
        ))}
      </div>

      {picker === 'mine' && (
        <MinePickerModal
          items={mineAssets}
          onPick={(asset) => { onRefFromMine(asset); setPicker(null) }}
          onClose={() => setPicker(null)}
        />
      )}
    </div>
  )
}

function MinePickerModal({ items, onPick, onClose }) {
  return (
    <div className="mine-picker-mask" onClick={(e) => { if (e.target === e.currentTarget) onClose() }}>
      <div className="mine-picker">
        <header>
          <span>从个人库选取参考图</span>
          <button type="button" onClick={onClose} aria-label="关闭"><X size={14} /></button>
        </header>
        <div className="mine-picker-grid">
          {items.map((it) => (
            <button key={it.id} type="button" className="mine-picker-item" onClick={() => onPick(it)}>
              <img src={it.url} alt={it.name} />
              <span>{it.name}</span>
            </button>
          ))}
        </div>
      </div>
    </div>
  )
}

function HistoryTab({ history, onApplyImage }) {
  if (history.length === 0) {
    return <div className="history-empty">还没有生成记录，去 AI 生成试一下吧</div>
  }
  return (
    <div className="asset-history">
      {history.map((item) => (
        <div
          key={item.id}
          className="history-item"
          draggable
          onDragStart={makeDragHandler(item.url, item.prompt)}
          title="拖动到袜版上即可应用"
        >
          <img src={item.url} alt={item.prompt} className="history-thumb-img" />
          <div className="history-info">
            <div className="history-prompt">{item.prompt}</div>
            <div className="history-meta">
              {item.refUrl ? '图片延申' : '可拖拽 · 双击应用'}
            </div>
          </div>
          <button
            type="button"
            className="history-apply"
            onClick={() => onApplyImage?.(item.url, item.prompt)}
          >
            应用
          </button>
        </div>
      ))}
    </div>
  )
}
